DROP DATABASE IF EXISTS example;
CREATE DATABASE example;
USE example;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id_users INT UNSIGNED PRIMARY KEY,
  name VARCHAR(255) NOT NULL
  );
  
 SELECT * FROM users;
 DESCRIBE users;